# /frontend/Containerfile

FROM public.ecr.aws/docker/library/node:20-slim

WORKDIR /app

COPY package*.json .

RUN npm ci --only=production
RUN npm cache clean --force
RUN npm rebuild lightningcss
RUN npm install lightningcss-linux-x64-gnu

COPY . . 

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0"]