# /infra-backend/podman-compose.yml
# RUTA:

services:
  db:
    image: public.ecr.aws/docker/library/postgres:16
    environment: 
      POSTGRES_DB: supportdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresl/postgres_data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ../backend
      dockerfile: Containerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:secret@db:5432/supportdb
      SECRET_KEY: EYELxlF6tqbI6Sf7Ic8YtWeO7MAoOef3UOFGY09aD5c
    depends_on:
      - db
    restart: unless-stopped
    network:
      - support-net

volumes:
  postgres_data:

networks:
  support-net:
    name: support-net
    external: true